@Rinha_de_backend_HostAddress = http://localhost:5173

GET {{Rinha_de_backend_HostAddress}}/clientes/1/extrato
Accept: application/json

###

POST {{Rinha_de_backend_HostAddress}}/clientes/1/transacoes
Accept: application/json
Content-Type: application/json

{
    "valor": 100,
    "tipo": "d",
    "descricao": "produto"
}
###
